import Head from "next/head";
import Header from "../components/Header";
import MovieList from "../components/MovieList";
import Nav from "../components/Nav";
import requests from "../utils/requests";

export default function Home({ results }) {
  // console.log(process.env.API_KEY);
  console.log(results);
  return (
    <div>
      <Head>
        <title>Hulu-clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header  */}
      <Header />
      <Nav />
      <MovieList results={results} />
    </div>
  );
}

export async function getServerSideProps(context) {
  // console.log(context);
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    }, // will be passed to the page component as props
  };
}
